server:
  port: 8000
spring:
  application:
    name: cambio-service
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/cambio_service?useTimezone=true&serverTimezone=UTC
    username: postgres
    password: root@root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    url: jdbc:postgresql://localhost:5432/cambio_service?useTimezone=true&serverTimezone=UTC
    schemas:
    - cambio_service
    user: postgres
    password: root@root